### ISSUE TITLE
Gros refatoring 

### ISSUE THREAD

**Issue by Embraser01** [kara71/RotINSA#12]
Salut !

J'ai fais un fork de se projet il ya quelques mois pour le refaire entièrement excepté les decks...

J'ai fait plusieurs choses :
- Mode hors-ligne (update automatique)
- Utilise Vue.js (donc single page)
- Gestionnaire de groupe de personnes
- Optimisation
- Responsive
- Ajout à l'écran d'accueil sur Android/WP/(iOS ?)

Niveau différences graphique, pas grand chose, seule chose, la différence entre Questions/actions/etc.. n'est pas visible pour l'instant.

Mais le projet est écrit en ES6 donc pas compatible avec IE ni les anciennes versions d'Android/iOS (avant 10.1)

La question est donc : est-ce que je fais une merge request sur ce repo, ou je garde cette version uniquement sur mon compte ?

Si vous voulez voir à quoi ça ressemble actuellement : https://embraser01.github.io/RotINSA/

**Comment by MathisHammel** [comment]
Bravo pour le gros refactoring, mais je pense qu'on va garder le projet tel qu'il est en ce moment.
Il y a des morceaux de ton UI que j'aime beaucoup (entrer une liste de joueurs par exemple) mais la partie avec les cartes est devenue beaucoup moins jolie (sur ma machine au moins). On avait aussi fait quelques modifs conséquentes depuis ton fork (par exemple le Konami code pour les fapchievements ou encore #10 mergée hier).

Tu aurais dû m'en parler au moment de forker, on aurait pu trouver un compromis plus sympa :)

**Comment by Embraser01** [comment]
Merci :) 

C'était surtout un projet d'un soir, pour découvrir VueJS et je pensais le repo inactif (d'ailleurs le nom de domaine _rotinsa.pro_ est mort), donc j'ai pas trop cherché à merge ici.

Vu que j'ai fait ça rapidement j'ai enlevé certaines fonctionnalités non triviales (~konami code notamment~). 
Pour les cartes je suis d'accord, il manque les couleurs et le type (ça va venir bientôt).

Concernant la dernière PR, de ce que j'ai vu, elle reprend en partie des changements que j'ai fait (~il me manque l'HTML escape pour les joueurs~).

En tout cas, bravo pour les decks 👍
